### ISSUE TITLE
Rebuild local pods

### ISSUE THREAD

**Issue by holgersindbaek** [HipByte/motion-cocoapods#107]
I have 2 pods, that I'm working on locally (bottom ones):

```
# Cocoapods
app.pods do
  pod 'pop', '~> 1.0'
  pod 'VBFPopFlatButton'
  pod 'DACircularProgress'
  pod 'UIImage+DecompressAndMap', '0.1.0'
  pod 'SwipeView', :path => 'vendor/LocalPods/SwipeView'
  pod 'IDMPhotoBrowser', :local => 'vendor/LocalPods/IDMPhotoBrowser'
end
```

Problem is, that they I have to do 'rake pod:install', each time I edit their files, to get them to rebuild. How can I make local pods rebuild automatically, if I edit their files?

**Comment by holgersindbaek** [comment]
Any suggestions?

**Comment by holgersindbaek** [comment]
Still no suggestions? It can't be true, that there's no possibility to edit a local pod and then rake the project again and see the result? How in the world would you edit pods in a project then?

**Comment by mfrawley** [comment]
This seems to work fine in XCode,but having the same issue so ... bump

**Comment by Watson1978** [comment]
The older `motion-cocoapods` and `CocaPods` will try to update Cocapods's repository by `rake pod:intall` and it take a long time to update repository.

Please use latest `motion-cocoapods` and `CocaPods`, they do not update repository by default.
