### ISSUE TITLE
Swift - Support for use_frameworks! in Podfile

### ISSUE THREAD

**Issue by mfrawley** [HipByte/motion-cocoapods#110]
0.36.0 of Cocoapods adds this directive and disables any attempt to include a Pod generated from Swift code for good reasons.

Is supporting Swift even possible? Having tried manually (creating and linking Swift frameworks) and reviewing the fixes the cocoapods team made, it seems as though the main issues are copying the Swift standard libs (libSwiftCore.dylib etc) into the build and re-signing the code afterwards. Would be nice to know though.

**Comment by j-wilkins** [comment]
Anyone figure anything out about this? Just bumped into it.

**Comment by ryanstout** [comment]
Same issue here, anyone have a solution?

**Comment by hgani** [comment]
This feature seems to be in the plan, but not a high priority yet. See https://github.com/HipByte/motion-cocoapods/issues/130
