### ISSUE TITLE
How do I 'link_with' my iOS extensions, specifically the Apple Watch extension?

### ISSUE THREAD

**Issue by BobaFaux** [HipByte/motion-cocoapods#113]
I am trying to use the MMWormhole pod with 'motion-cocoapods' but I am having trouble seeing where I can link my pods into both my iPhone target and Apple Watch target?

**Comment by Watson1978** [comment]
Please update `motion-cocoapods`.
The latest `motion-cocoapods` will support Apple Watch by https://github.com/HipByte/motion-cocoapods/commit/598f7b1f0abb92d4e24e6a15f34bdcb0b98d29cf
