### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysope on pod install

### ISSUE THREAD

**Issue by rromanchuk** [HipByte/motion-cocoapods#115]
https://github.com/rromanchuk/BrokenCocoapods

**Comment by MarkVillacampa** [comment]
Use this

```
pod 'AWSCognito'
```

 instead of this

```
pod 'AWSCognitoSync'
```

That should solve the problem. They seem to be an alias, but the second podspec depends on the first, hence duplicating some resources and causing this error.

**Comment by rromanchuk** [comment]
yeah just updated that, i seem to be getting the same issue though

**Comment by rromanchuk** [comment]
`rbenv sudo rake:pod install` worked... but not good obviously
