### ISSUE TITLE
"[BUG] Segmentation fault" when trying to install AsyncDisplayKit

### ISSUE THREAD

**Issue by holgersindbaek** [HipByte/motion-cocoapods#117]
I'm having some issues installing Facebook's AsyncDisplayKit library using cocoa pods. I'm getting this peculiar error in the terminal when I try to run the app:

https://gist.github.com/holgersindbaek/fdc4793f3304f69dfb7b

Test project:

https://github.com/holgersindbaek/test-project

Think it might have something to do with motion-cocoapods. What do you think?

**Comment by holgersindbaek** [comment]
No suggestions?

**Comment by Watson1978** [comment]
This problem is related to system bundled BridgeSupport released by Apple.
Since RubyMotion v3.14, we have bundled our `BridgeSupport`.
If you use latest RubyMotion, you can solve your issue.
