### ISSUE TITLE
Errno::EACCES: Permission denied - vendor/Pods/Resources/FBUserSettingsViewResources.bundle/Contents/Resources/en.lproj/Localizable.strings

### ISSUE THREAD

**Issue by ijpiantanida** [HipByte/motion-cocoapods#118]
Facebook-iOS-SDK version (= 3.17.0)
motion-cocoapods 1.7.1

The offending line is `motion-cocoapods-1.7.1/lib/motion/project/cocoapods.rb:253`
```
FileUtils.cp_r(file, resources_dir) if file.exist?
```

I think it's because the file already exists on resources_dir but it only has read permission.

**Comment by Watson1978** [comment]
This issue should be fixed with master branch.
We will release new version soon.
