### ISSUE TITLE
LoadError: cannot load such file on v1.7.3

### ISSUE THREAD

**Issue by divmgl** [HipByte/motion-cocoapods#123]
`motion-cocoapods@1.7.3` cannot be installed correctly from scratch on my machine.

Gemfile
```
source 'https://rubygems.org'

gem 'rake'
gem 'motion-kit'
gem 'motion-cocoapods'
```

Rakefile
```
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'rubygems'
require 'bundler'
Bundler.require
```

After running `bundle`, running `rake pod:install` returns the following message:

```
LoadError: cannot load such file -- motion/project/cocoapods
/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.7.3/lib/motion-cocoapods.rb:25:in `require'
```

After reverting back to `v1.7.2` everything is working as expected.

**Comment by MarkVillacampa** [comment]
I cannot reproduce this. Can you upload a test project that reproduces this issue?

**Comment by divmgl** [comment]
https://github.com/divmgl/cocoapods-error

**Comment by divmgl** [comment]
Deleting `/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.7.3/` has fixed the issue for me. Must have been a corrupt download.

**Comment by divmgl** [comment]
For anyone that might be seeing this: the problem was in the file permissions in the `libs` folder.

**Comment by jlnr** [comment]
I'm experiencing the same issue here. No matter if I install the gem using `bundle` or `sudo gem install`, the files in `lib/motion` end up with permissions 600. I have to manually `sudo chmod 644` them to be able to use the gem.

I think this might actually be a bug in the gem? I'm on 10.10.5, using Apple's system Ruby.

**Comment by jlnr** [comment]
@MarkVillacampa If I untar `motion-cocoapods-1.7.3.gem` and then look at `data.tar.gz`, I see:

```
jlnr$ tar -tvzf /Users/jlnr/Desktop/motion-cocoapods-1.7.3.gem/data.tar.gz 
-rw-r--r--  0 wheel  wheel    1330 31 Jul 14:39 LICENSE
-rw-r--r--  0 wheel  wheel    4258 31 Jul 14:39 README.md
-rw-r--r--  0 wheel  wheel    1437 31 Jul 14:39 lib/motion-cocoapods.rb
-rw-------  0 wheel  wheel   13401 31 Jul 14:39 lib/motion/project/cocoapods.rb
-rw-------  0 wheel  wheel    1444 31 Jul 14:39 lib/motion/project/version.rb
```

Files in other gems seem to consistently use 644.

**Comment by divmgl** [comment]
@jlnr it definitely looks like a gem packaging error. I stopped receiving this problem after I fixed the permissions in the `cocoapods` folder.

**Comment by MarkVillacampa** [comment]
Sorry about this, I have pushed version 1.7.4 with fixed permissions.
