### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by megeek** [HipByte/motion-cocoapods#126]
when trying to use motion-cocoapods on a tvOS project, I get the error:
    ERROR! Unknown CocoaPods platform: AppleTVOS

**Comment by egze** [comment]
+1
Please add support!

**Comment by Watson1978** [comment]
To build CocoaPods library, it need http://hipbyte.myjetbrains.com/youtrack/issue/RM-983 fixing. 
It will be shipped with next RubyMotion version.
