### ISSUE TITLE
Support iOS dynamic frameworks

### ISSUE THREAD

**Issue by MarkVillacampa** [HipByte/motion-cocoapods#130]
We should support iOS dynamic frameworks via Cocoapod's "use_frameworks!" option.

The only tricky part is differentiating fake iOS static frameworks and iOS 8+ dynamic frameworks.

**Comment by steipete** [comment]
Thanks for planning to add this. This is currently a blocker for supporting [PSPDFKit](https://pspdfkit.com/) in RubyMotion, and we expect more and more vendors switching to dynamic frameworks as they offer many advantages and better namespacing compared to statically linked libraries.

The `use_frameworks!` directive in Cocoapods will be applied to all pods - so it simply will produce linker errors for fake frameworks. Thus, your worry about differentiating fake iOS static frameworks and "real" dynamic ones shouldn't be an issue.

**Comment by buley** [comment]
As more and more pods are rolled out as Swift-only, this is making it harder and harder to get things done in Rubymotion.   

> Installing SwiftyJSON (2.3.2)
> rake aborted!
> Pod::Informative: [!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: SwiftyJSON

**Comment by MarkVillacampa** [comment]
@buley supporting dynamic frameworks does not necessarily mean supporting Pods written in Swift. We will have to look into that separately and possibly add support in RubyMotion core (not motion-cocoapods). However, there are ObjC equivalents for virtually any Swift-only library, so this has not been a priority so far.

**Comment by marlabz6** [comment]
I agree with @buley , I'm finding the newer cocoapods, with functionality that I would like to use, are written in Swift, so I have to spend time trying to find an Obj-C cocoapod that comes close, but usually is not as sexy.

**Comment by n-studio** [comment]
Turbolinks-iOS (https://github.com/turbolinks/turbolinks-ios) may become a major Swift framework in Ruby community and it requires `use_frameworks!`.

I'm looking forward to being able to write a Rails app and make an Android/iOS hybrid app out of it with RubyMotion! That would be the dream and a killer feature for RubyMotion. Supporting `use_frameworks!` should be a priority IMHO. cc @lrz

**Comment by hgani** [comment]
@MarkVillacampa may we request this feature to be prioritized?

We are excited about Turbolinks 5 (https://github.com/turbolinks/turbolinks-ios) and would like to use it in our Rubymotion app.

Thanks

**Comment by apinrdw** [comment]
+1

**Comment by xcoatl** [comment]
Just to be aware that this problem will increase with the time, maybe a year ago the number of Swift only libraries was small, but right now there are more and more ...

**Comment by Lax** [comment]
Since swift is going into mainstream, we find more and more swift-only(and swift-first) pods right now.
So if anyone has an idea to get things better?
