### ISSUE TITLE
Objective-C stub for message not precompiled for DTCoreText

### ISSUE THREAD

**Issue by egze** [HipByte/motion-cocoapods#139]
This is what I have in the Rakefile
```
app.pods do
  pod 'DTCoreText'
end
```

`rake pod:install` runs fine. The app starts and then I try to test a simple example in REPL.

```
string = "<p>test</p>"
data = string.dataUsingEncoding(NSUTF8StringEncoding)
attrString = NSAttributedString.alloc.initWithHTMLData(data, documentAttributes: nil)

Objective-C stub for message `initWithHTMLData:documentAttributes:' type `@@:@^@' not precompiled. Make sure you properly link with the framework or library that defines this message.
Remote process has quit.
```

I really need `DTCoreText`, but I have no idea how to fix it. Please help.

**Comment by jjaffeux** [comment]
@egze Did you try in code and not in the REPL ?

**Comment by egze** [comment]
I have now. It works.

Why doesn't REPL like it then?

**Comment by jjaffeux** [comment]
Sadly the REPL has some limitations : http://hipbyte.myjetbrains.com/youtrack/issue/RM-21
