### ISSUE TITLE
`use_frameworks!` and RubyMotion version

### ISSUE THREAD

**Issue by afestein** [HipByte/motion-cocoapods#143]
Hi there, I have a question about https://github.com/HipByte/motion-cocoapods/commit/2ff9de0b10f2fe9e94c9d5134111481a56af52d5 - I'm trying to use the `use_frameworks!` method, however it seems like this isn't yet supported in RubyMotion 4.17. 

@Watson1978 has kindly updated the Readme, however I'm confused because I can't upgrade RubyMotion (4.18 doesn't seem to have been released yet). 

Am I missing something? Any help greatly appreciated.

**Comment by Watson1978** [comment]
The feature needs new version (see https://github.com/HipByte/motion-cocoapods/commit/2ff9de0b10f2fe9e94c9d5134111481a56af52d5)

Please ask release plan to @lrz, because I had left Hipbyte.

**Comment by afestein** [comment]
Thanks @Watson1978. Are you able to shed some light on a release plan for RubyMotion 4.18 @lrz?

**Comment by lrz** [comment]
@afestein the release is on its way, just a matter of a few days now!

**Comment by andrewhavens** [comment]
RubyMotion 4.18 has now been released, but it seems that the latest version of this gem (1.8.1) does not include the recent addition of `use_frameworks!`.

Until a new version of this gem is released, you can use the master branch by updating your Gemfile like this:

    gem 'motion-cocoapods', github: 'HipByte/motion-cocoapods'

**Comment by Watson1978** [comment]
Released 1.9.0
