### ISSUE TITLE
Error parsing strings in FacebookSDK

### ISSUE THREAD

**Issue by buley** [HipByte/motion-cocoapods#144]
I'm sure this is not the fault of `motion-cocoapods`, but I've encountered a snafu with the `FacebookSDK` library and I wonder if `motion-cocoapods` could do anything to prevent the build from crashing when using this pod.

>     pod 'FBSDKCoreKit'

Just including this pod seems to be enough to break a build. The strings file erring out is empty, I believe. Maybe there's a `/usr/bin/plutil -convert` flag that would work to allow it to continue along to plug along after this parse error? Here's a log:
https://gist.github.com/buley/a70b0098df3701b1b168a8e45abdea03

**Comment by willem-h** [comment]
There's a fix for this in the Facebook iOS SDK dev branch (https://github.com/facebook/facebook-ios-sdk/pull/867). If you point your source to that it should work.
