### ISSUE TITLE
Run Pods-RubyMotion-frameworks.sh as part of build

### ISSUE THREAD

**Issue by jgritman** [HipByte/motion-cocoapods#147]
The `Pods-RubyMotion-frameworks.sh` is parsed as part of the build (see [here](https://github.com/HipByte/motion-cocoapods/blob/master/lib/motion/project/cocoapods.rb#L526)) but never executed. For my app, we use the [Smooch framework](https://github.com/smooch/smooch-ios) which is shipped with multiple architecures bundled for different simulators. 

If I submit my app to TestFlight without removing those architectures, it will get rejected. The `frameworks` script strips those out ([documentation here](https://github.com/smooch/smooch-ios/issues/102)).

I was previously using `motion-carthage` alongside `motion-cocoapods` to install this framework, but it no longer works as of Xcode 9/High Sierra. I've tried fixing this on my own but I don't understand the build lifecycle enough to populate the correct environment variables when executing the script.

**Comment by amirrajan** [comment]
This is also confirmed in Mojave and Xcode 10.1 (the .sh files don't seem to be generated at all anymore in fact). It should be a pretty straight forward fix. I'll create a new issue with full info about the problem and reference this issue for record/posterity.

**Comment by katsuyoshi** [comment]
When I back to cocoapods version 1.5.3,  missing .sh file is fixed.
But app crashes by NoMethodError. I guess bridge support is not working succeed. 

Gemfile:

```
gem 'cocoapods','1.5.3'
gem 'motion-cocoapods'
```

Error message:

```
Terminating app due to uncaught exception 'NoMethodError', reason: 'app/model/admob.rb:26:in `setup_banner': undefined method `request' for GADRequest:Class (NoMethodError)
```

**Comment by katsuyoshi** [comment]
When I specified the older version of AdMob, the error was disappeared.
Cause the error was AdMob. It had not related to this issue.

Rakefile

```
app.pods do
  pod 'Firebase/AdMob', '3.12.0'
end
```

**Comment by amirrajan** [comment]
There was a recent PR that was merged in: https://github.com/HipByte/motion-cocoapods/pull/151

@katsuyoshi can you confirm if you're still having the issue or not?

**Comment by katsuyoshi** [comment]
@amirrajan 
Everything is fine even if  AdMob without specifying version too.
Fabulous!

**Comment by amirrajan** [comment]
Gem has been pushed also. Thanks for verifying.
