### ISSUE TITLE
Fails with Cocoapods 1.7.0 `Pod::Installer#installation_options` is now private

### ISSUE THREAD

**Issue by eamonn-webster** [HipByte/motion-cocoapods#152]
Can be reproduced by 
`bundle update`
and then
`rake spec`

`Pod::Installer#installation_options` is now private

NoMethodError: private method `installation_options' called for #<Pod::Installer:0x00007fe656ca3bb0>
	~/projects/motion-cocoapods/lib/motion/project/cocoapods.rb:240:in `install!': motion-cocoapods - provides a list of the activated pods on #inspect, which is used in `rake config`
	~/projects/motion-cocoapods/lib/motion/project/cocoapods.rb:577:in `block (2 levels) in <top (required)>'

**Comment by AaronLasseigne** [comment]
I started looking into this and the tests for this gem start failing with cocoapods 1.6.0. We might need to take case of that first.

**Comment by AaronLasseigne** [comment]
see #153 for the 1.6.0 issue

**Comment by tsugua** [comment]
This is happening to me on macOS 11.0.1 Big Sur. RM 7.14, Xcode 12.1

`NoMethodError: private method `installation_options' called for #<Pod::Installer:0x00007fa544a0f410>
/Users/shaun/.rvm/gems/ruby-2.6.4/gems/motion-cocoapods-1.9.2/lib/motion/project/cocoapods.rb:240:in `install!'`

**Comment by tsugua** [comment]
Please disregard, bundle update didn't seem to move me to motion-cocoapods 1.10.0. Once I set the minimum gem target to 1.10.0 it worked fine!
