### ISSUE TITLE
pod 'Appboy-iOS-SDK/AppboyKit' pulls in LIBRARY_SEARCH_PATHS twice...

### ISSUE THREAD

**Issue by interhive** [HipByte/motion-cocoapods#91]
We're using the Appboy pod:

``` ruby
pod 'Appboy-iOS-SDK/AppboyKit'
```

This results in the following line `Pods.xcconfig`:

```
LIBRARY_SEARCH_PATHS = "$(PODS_ROOT)/Appboy-iOS-SDK/AppboyKit" "$(PODS_ROOT)/Appboy-iOS-SDK/AppboyKit"
```

Also, in `Pods-Appboy-iOS-SDK.xcconfig`:

```
PODS_APPBOY_IOS_SDK_LIBRARY_SEARCH_PATHS = "$(PODS_ROOT)/Appboy-iOS-SDK/AppboyKit" "$(PODS_ROOT)/Appboy-iOS-SDK/AppboyKit"
```

Checked out the spec and it's only bringing it in once.

In any case, this results in a compile error. Removing the duplicate in both of the above files results in a clean compile.

Thanks!

**Comment by kevindelord** [comment]
I currently have this problem as well.
I'm digging around as I have the following compilation error:
````
duplicate symbol _OBJC_METACLASS_$_ABKIdentifierForAdvertisingProvider in:
    /fullPath/Build/Products/Debug-iphonesimulator/libPods-Appboy-iOS-SDK.a(ABKIdentifierForAdvertisingProvider-34CAB08EA8E0C6CD.o)
duplicate symbol _OBJC_CLASS_$_ABKIdentifierForAdvertisingProvider in:
    /fullPath/Build/Products/Debug-iphonesimulator/libPods-Appboy-iOS-SDK.a(ABKIdentifierForAdvertisingProvider-34CAB08EA8E0C6CD.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````
After hours looking for a configuration problem, I found the double include in the `LIBRARY_SEARCH_PATHS`.

Does anyone have an idea?

**Comment by mdwem** [comment]
Same problem..any solution

**Comment by kevindelord** [comment]
We fix the problem by recreating the Xcode project. At that time, we were maintaining a very old project with an old xcode structure. Somehow installing pods and dependencies broke the double import and corrupted the build.
My solution was to create a fresh new Xcode 6.x project and reimport all code and configuration. It took me about 2 hours but then... the build worked :+1:

**Comment by mdwem** [comment]
Hi,
I am almost in the very end of project.Creating a new not feasible now.Any other fix.
Thanks,

**Comment by kevindelord** [comment]
My app was already on the AppStore. I needed a fix to go further as you right now I guess.
No one can easily reproduce this bug because it does not happen with new project setups.
After hours fighting against the computer, I figured out that my old-xcode4 structure was valid for AppBoy+Cocoapods.

You don't have to create a new project. Just a new .xcodeproj file.
Xcode > File > New > Project...
And then import all your sources.

Good luck :)

**Comment by mdwem** [comment]
Hi,
I got it working by removing 'duplicate symbol' in library search path as it was being repeated twice.
Thanks for you help@kevindelord

**Comment by Watson1978** [comment]
Please update `motion-cocoapods` & `CocoaPods`.

Now,
```
pod 'Appboy-iOS-SDK/AppboyKit'
```
will generate 
```
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Appboy-iOS-SDK/AppboyKit" "$PODS_CONFIGURATION_BUILD_DIR/SDWebImage"
```
And looks for me that it would works well.
