### ISSUE TITLE
How to change Pods.bridgesupport file manually?

### ISSUE THREAD

**Issue by okawa14all** [HipByte/motion-cocoapods#93]
I tried to login through Facebook by using Parse-iOS-SDK.

```
app.pods do
  pod 'Parse-iOS-SDK'
end
```

Unfortunately there is a known bug in the way the Parse SDK bridge files are generated and a simple workaround is known.
https://groups.google.com/forum/#!msg/rubymotion/36WCWPPkPdc/kBCDS-DOSjsJ

I changed `vendor/Pods/build-iPhoneSimulator/Pods.bridgesupport` manually and run app `rake`, but i could'nt solve.

How can I change Pods.bridgesupport file manually?

**Comment by chunlea** [comment]
@Watson1978 Now I am using the parse-ios-SDK 1.6.1, and seems your patch doesn't works any more. Any update?

```
Objective-C stub for message `logInWithPermissions:block:' type `v@:@@?' not precompiled. Make sure you properly link with the framework or library that defines this message.
```

**Comment by rromanchuk** [comment]
with 4.0 Objective-C stub for message `startWithCompletionHandler:' type `@@:@?' not precompiled. Make sure you properly link with the framework or library that defines this message.
signal %d, info %p, uapVoid %p
